#!/usr/bin/env bash

set -euo pipefail

curl "${HEALTHCHECKS_BACKUP_HOMEDIR}/start"

cd /home/will
/usr/local/bin/duplicacy backup -stats

if [[ -d /run/media/will/external_hd ]] ; then
    rsync -azh /home/will '/run/media/will/external_hd/WD Passport/Backups/2020_linux_laptop_homedir'
else
    echo "External drive not connected"
fi

curl "$HEALTHCHECKS_BACKUP_HOMEDIR"
