#!/usr/bin/env bash

set -euo pipefail


if [[ -d /run/media/will/external_hd ]] ; then
    curl "${HEALTHCHECKS_BACKUP_EXTERNALHDD}/start"

    cd /run/media/will/external_hd
    /usr/local/bin/duplicacy backup -stats

    curl "$HEALTHCHECKS_BACKUP_EXTERNALHDD"
else
    echo "External drive not connected"
fi
