#!/usr/bin/env bash

set -euo pipefail

if [[ -d /run/media/will/external_hd ]] ; then
    cd /run/media/will/external_hd
    /usr/local/bin/duplicacy backup -stats
else
    echo "External drive not connected"
fi




